import { Box, Button } from '@chakra-ui/react';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';

interface TakeTurnProps {
  department: string;
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const department = context.params?.department;

  return {
    props: { department: department },
  };
}

export default function TakeTurn({ department }: TakeTurnProps) {
  // - Esta pagina sera donde los usuarios sacaran sus turnos

  // --------- SACAR UN TURNO --------- //
  const takeTurn = async () => {
    await fetch('/api/createTurn', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        department_name: department,
      }),
    });
  };

  return (
    <>
      <Head>
        <title>UAL - Take Turn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Sacar un turno - {department}
        <Box>Aqui se va a mostrar las personas que hay en la fila</Box>
        <Box>
          <Button>Cancelar</Button>
          <Button onClick={takeTurn}>Sacar turno</Button>
        </Box>
      </main>
    </>
  );
}
