import MyUserCard from '@/components/cards/myUserCard';
import NewUserCard from '@/components/cards/newUserCard';
import NavBar from '@/components/layout/navbar';
import LoaderSpinner from '@/components/loaderSpinner';
import { withSessionSsr } from '@/lib/auth/witSession';
import useHasMounted from '@/lib/hasMounted';
import { Box, Grid, GridItem } from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export interface UsersPageProps {
  user: any;
}

export const getServerSideProps = withSessionSsr(
  async ({ req, res }: { req: any; res: any }) => {
    const user = req.session.user;

    if (!user) {
      return {
        props: { user: null },
      };
    }

    return {
      props: { user },
    };
  }
);

export default function UsersPage({ user }: UsersPageProps) {
  // - Esta es la pagina de inicio del sistema para empleados
  const router = useRouter();
  const hasMounted = useHasMounted();

  // ------- USESTATE DECLARATIONS ------- //
  const [myUser, setMyUser] = useState(null);

  // ------- OBTENER MI USUARIO ------- //
  const getMyUser = async () => {
    await fetch(`/api/users/getUser?user_id=${user._id}`).then(async (res) => {
      if (res.status == 200) {
        const data = await res.json();

        // - Si el rol del usuario fue actualizado cerrar sesion
        if (data.user_data.rol != user.rol) {
          await fetch('/api/logout');
          router.push('/login');
        }

        setMyUser(data.user_data);
      }
    });
  };

  useEffect(() => {
    getMyUser();

    // - If the user is not logged in, redirect to /login
    if (!user || (user.rol != 'admin' && user.rol != 'superadmin')) {
      router.push('/login');
    }
  });

  // - If the user is not logged in, redirect to /login
  if (!user || (user.rol != 'admin' && user.rol != 'superadmin')) {
    return <div>Redirecting...</div>;
  }

  // - Page
  return (
    <>
      <Head>
        <title>UAL - Usuarios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar rol={user.rol} name={user.username} />

        {/* PAGINA DE USUARIOS */}
        <Box px={3} py={4}>
          <h1>Gestion de usuarios</h1>

          <Grid templateColumns="repeat(4, 1fr)" gap={0}>
            {/* CARD PARA NUEVO USUARIO */}
            <GridItem>
              {hasMounted ? (
                <NewUserCard userRol={user.rol} />
              ) : (
                <LoaderSpinner paddingY="10rem" size="xl" />
              )}
            </GridItem>

            {/* CARD PARA VER MI USUARIO */}
            <GridItem>
              {myUser ? (
                <MyUserCard user={myUser} reloadUser={getMyUser} />
              ) : (
                <LoaderSpinner paddingY="10rem" size="xl" />
              )}
            </GridItem>
          </Grid>
        </Box>
      </main>
    </>
  );
}
