import { withSessionSsr } from '@/lib/auth/witSession';
import connectDB from '@/models/mongoConnection';
import Department from '@/models/mongoSchemas/departmentSchema';
import { Box, Button } from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/router';

interface HomeProps {
  user: any;
  departments: any;
}

export const getServerSideProps = withSessionSsr(
  async ({ req, res }: { req: any; res: any }) => {
    await connectDB();

    const user = req.session.user;
    const departmentsFetching = await Department.find({}).sort({
      createdAt: -1,
    });

    const departments = JSON.parse(JSON.stringify(departmentsFetching));

    if (!user) {
      return {
        props: { user: null, departments: departments },
      };
    }

    return {
      props: { user: user, departments: departments },
    };
  }
);

export default function Home({ user, departments }: HomeProps) {
  // - Esta pagina sera donde los usuarios sacaran sus turnos
  // ------- HOOKS ------- //
  const router = useRouter();

  return (
    <>
      <Head>
        <title>UAL - Turnos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Selecciona un departamento</h1>

        <Box>
          {departments.map((department: any) => (
            <Box key={department._id}>
              <Button
                onClick={() => {
                  router.push(`/take-turn/${department.name}`);
                }}
              >
                {department.name}
              </Button>
            </Box>
          ))}
        </Box>
      </main>
    </>
  );
}
