import {
  Box,
  Button,
  Flex,
  FormControl,
  FormLabel,
  Heading,
  Input,
  Stack,
  useColorModeValue,
} from '@chakra-ui/react';
import Head from 'next/head';
import router from 'next/router';
import { useState } from 'react';

export default function Login() {
  // ----------- USESTATE DECLARATIONS ----------- //
  const [mail, setMail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = async () => {
    const response = await fetch('/api/sessions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ mail, password }),
    });

    if (response.ok) {
      return router.push('/system');
    } else {
      alert('Usuario o contraseña incorrectos');
    }
  };

  return (
    <>
      {/* // ----------- HEAD ----------- // */}
      <Head>
        <title>UAL - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* // ----------- MAIN ----------- // */}
      <main>
        <Flex
          minH={'100vh'}
          align={'center'}
          justify={'center'}
          bg={useColorModeValue('gray.50', 'gray.800')}
        >
          <Stack spacing={8} mx={'auto'} maxW={'lg'} py={12} px={6}>
            <Stack align={'center'}>
              <Heading fontSize={'3xl'}>
                Inicia sesion con tu cuenta UAL
              </Heading>
            </Stack>

            <Box
              rounded={'lg'}
              bg={useColorModeValue('white', 'gray.700')}
              boxShadow={'lg'}
              p={8}
            >
              <Stack spacing={4}>
                <FormControl id="email">
                  <FormLabel>Correo electronico:</FormLabel>
                  <Input
                    type="email"
                    value={mail}
                    onChange={(e) => {
                      setMail(e.target.value);
                    }}
                  />
                </FormControl>

                <FormControl id="password">
                  <FormLabel>Contraseña:</FormLabel>
                  <Input
                    type="password"
                    value={password}
                    onChange={(e) => {
                      setPassword(e.target.value);
                    }}
                  />
                </FormControl>

                <Stack spacing={10}>
                  <Button
                    bg={'blue.400'}
                    color={'white'}
                    _hover={{
                      bg: 'blue.500',
                    }}
                    onClick={handleSubmit}
                  >
                    Iniciar Sesion
                  </Button>
                </Stack>
              </Stack>
            </Box>
          </Stack>
        </Flex>
      </main>
    </>
  );
}
