import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

interface TakeTurnProps {
  turn_id: string;
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const turn_id = context.query.turn_id;

  return {
    props: { turn_id: turn_id },
  };
}

export default function TakeTurn({ turn_id }: TakeTurnProps) {
  // - Esta pagina sera donde los usuarios sacaran sus turnos
  // --------- HOOKS --------- //
  const router = useRouter();

  return (
    <>
      <Head>
        <title>UAL - My Turn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Tu turno : {turn_id}</main>
    </>
  );
}
