import connectDB from '@/models/mongoConnection';
import Turn from '@/models/mongoSchemas/turnScheme';
import { Box } from '@chakra-ui/react';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

interface TakeTurnProps {
  turn_data: any;
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  await connectDB();

  const turn_id = context.query.turn_id;

  const turnFetching = await Turn.findOne({
    _id: turn_id,
    $or: [{ status: 'pending' }, { status: 'attending' }],
  });

  const turn = JSON.parse(JSON.stringify(turnFetching));

  if (!turn) {
    return {
      notFound: true,
    };
  }

  return {
    props: { turn_data: turn },
  };
}

export default function TakeTurn({ turn_data }: TakeTurnProps) {
  // - Esta pagina sera donde los usuarios sacaran sus turnos
  // --------- HOOKS --------- //
  const router = useRouter();

  return (
    <>
      <Head>
        <title>UAL - My Turn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Tu turno : {turn_data.turn}{' '}
        <Box>id: {turn_data._id.slice(turn_data._id.length - 5)}</Box>
      </main>
    </>
  );
}
