import NavBar from '@/components/layout/navbar';
import { withSessionSsr } from '@/lib/auth/witSession';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export interface SystemHomeProps {
  user: any;
}

export const getServerSideProps = withSessionSsr(
  async ({ req, res }: { req: any; res: any }) => {
    const user = req.session.user;

    if (!user) {
      return {
        props: { user: null },
      };
    }

    return {
      props: { user },
    };
  }
);

export default function SystemHome({ user }: SystemHomeProps) {
  // - Esta es la pagina de inicio del sistema para empleados
  const router = useRouter();

  useEffect(() => {
    // - If the user is not logged in, redirect to /login
    if (!user) {
      router.push('/login');
    }
  }, []);

  // - If the user is not logged in, redirect to /login
  if (!user) {
    return <div>Redirecting...</div>;
  }

  // - Page
  return (
    <>
      <Head>
        <title>UAL - Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar rol={user.rol} name={user.username} />

        <h1>Hello {user.username}</h1>
        <p>Secret Content</p>
      </main>
    </>
  );
}
