import { withSessionSsr } from '@/lib/auth/witSession';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export interface SystemHomeProps {
  user: any;
}

export const getServerSideProps = withSessionSsr(
  async ({ req, res }: { req: any; res: any }) => {
    const user = req.session.user;

    if (!user) {
      return {
        props: { user: null },
      };
    }

    return {
      props: { user },
    };
  }
);

export default function SystemHome({ user }: SystemHomeProps) {
  // - Esta es la pagina de inicio del sistema para empleados
  const router = useRouter();

  // ------- USESTATE DECLARATIONS ------- //
  const [myUser, setMyUser] = useState<any>(null);

  // ------- OBTENER MI USUARIO ------- //
  const getMyUser = async () => {
    await fetch(`/api/users/getUser?user_id=${user._id}`).then(async (res) => {
      if (res.status == 200) {
        const data = await res.json();

        // - Si el rol del usuario fue actualizado cerrar sesion
        if (data.user_data.rol != user.rol) {
          await fetch('/api/logout');
          router.push('/login');
        }

        setMyUser(data.user_data);
      }
    });
  };

  useEffect(() => {
    getMyUser();

    // - If the user is not logged in, redirect to /login
    if (!user) {
      router.push('/login');
    }

    if (user.rol != 'asesor') {
      router.push('/system/admin/departments');
    }

    if (user.rol == 'asesor') {
      router.push('/system/asesor/my-service-point');
    }
  });

  // - If the user is not logged in, redirect to /login
  if (!user) {
    return <div>Redirecting...</div>;
  }

  // - Page
  return (
    <>
      <Head>
        <title>UAL - Sistema</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-general">
        <h1>Redireccionando</h1>
      </main>
    </>
  );
}
