import { withSessionSsr } from '@/lib/auth/witSession';
import { Button } from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export interface SystemHomeProps {
  user: any;
}

export const getServerSideProps = withSessionSsr(
  async ({ req, res }: { req: any; res: any }) => {
    const user = req.session.user;

    if (!user) {
      return {
        props: { user: null },
      };
    }

    return {
      props: { user },
    };
  }
);

export default function SystemHome({ user }: SystemHomeProps) {
  const router = useRouter();

  useEffect(() => {
    if (!user) {
      router.push('/login');
    }
  }, []);

  if (!user) {
    return <div>Redirecting...</div>;
  }

  return (
    <>
      <Head>
        <title>UAL - Turnos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello {user.username}</h1>
        <p>Secret Content</p>

        <Button
          onClick={async () => {
            await fetch('/api/logout');
          }}
        >
          LOGOUT
        </Button>
      </main>
    </>
  );
}
