import LoaderSpinner from '@/components/loaderSpinner';
import ServicePointTurnBox from '@/components/servicePointTurnBox';
import connectDB from '@/models/mongoConnection';
import Department from '@/models/mongoSchemas/departmentSchema';
import { Box, useToast } from '@chakra-ui/react';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

interface TakeTurnProps {
  department: any;
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  await connectDB();

  const department = context.params?.department;

  const validateDepartment = await Department.findOne({
    name: department,
  });

  if (!validateDepartment) {
    return {
      notFound: true,
    };
  }

  return {
    props: { department: JSON.parse(JSON.stringify(validateDepartment)) },
  };
}

export default function TakeTurn({ department }: TakeTurnProps) {
  // - Esta pagina sera donde los usuarios sacaran sus turnos
  // --------- HOOKS --------- //
  const router = useRouter();
  const toast = useToast();

  const [queue, setQueue] = useState<any>(null);
  const [servicePoints, setServicePoints] = useState<any>(null);

  // --------- OBTENER LA FILA DE TURNOS --------- //
  const getQueue = async () => {
    await fetch(`/api/getQueue?department_name=${department.name}`).then(
      async (res) => {
        const data = await res.json();

        if (res.status == 200) {
          setQueue(data.queue_data);
        } else if (res.status == 404) {
          setQueue('404');
        } else if (res.status == 400) {
          toast({
            title: 'Error al consultar la fila',
            description: data.message,
            variant: 'left-accent',
            status: 'error',
            duration: 9000,
            isClosable: true,
          });
        } else {
          toast({
            title: 'Error al consultar la fila',
            description: 'Error desconocido',
            status: 'error',
            duration: 9000,
            isClosable: true,
          });
        }
      }
    );

    setTimeout(() => {
      getQueue();
    }, 5000);
  };

  const getServicePoints = async () => {
    await fetch(
      `/api/servicePoints/getDepartmentServicePoints?department_id=${department._id}`
    ).then(async (res) => {
      const data = await res.json();

      if (res.status == 200) {
        setServicePoints(data.service_points_data);
      } else if (res.status == 404) {
        setServicePoints('404');
      } else if (res.status == 400) {
        setServicePoints('400');
      } else {
        toast({
          title: 'Error al consultar los puntos de servicio',
          description: 'Error desconocido',
          status: 'error',
          duration: 9000,
          isClosable: true,
        });
      }
    });
  };

  // --------- USE EFFECT --------- //
  useEffect(() => {
    getQueue();
    getServicePoints();
  }, []);

  return (
    <>
      <Head>
        <title>UAL - See turns</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {department.name}

        <Box>
          {queue == null ? (
            <>
              <LoaderSpinner size="xl" paddingY="2rem" />
            </>
          ) : queue == '404' ? (
            <>No hay fila</>
          ) : (
            <>
              {queue.map((turn: any, i: any) => {
                return (
                  <Box key={turn._id}>
                    {i == 0 ? 'Siguiente: ' : null}
                    {turn.turn}
                  </Box>
                );
              })}
            </>
          )}
        </Box>

        <Box>
          {servicePoints == null ? (
            <>Cargando...</>
          ) : servicePoints == '400' ? (
            <>No se han creado puntos de servicio para este departamento</>
          ) : (
            <>
              {servicePoints.map((servicePoint: any) => {
                return (
                  <>
                    {servicePoint.available ? (
                      <>
                        <ServicePointTurnBox
                          key={servicePoint._id}
                          servicePointId={servicePoint._id}
                        />
                      </>
                    ) : null}
                  </>
                );
              })}
            </>
          )}
        </Box>
      </main>
    </>
  );
}
